### PR TITLE
Bug fixes #258 and #257

### LINKED ISSUE #239: Individual drop color is calculated wrong when adding/removing drops from viewport
I use inidividually colored drops, which is colored based on some data related to each drop.
When panning or zooming the timelines and new drops appear, the color changes on all drops on that line, instead of only the new drop.

Please see this example: https://a.uguu.se/UP4TCkFVGhWg_2018-05-02_13-02-12.mp4
It is expected that the red drop remains red and not change to green.

* EventDrops version: 1.2.0

### LINKED ISSUE #241: drop color function or radius is not called again to fill or resize on merge.
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](https://stackoverflow.com/questions/tagged/event-drops).

**What you were expecting:**
I was expecting my color function to work properly and color events based on type. It does so initially but on zoom it fails to reflect the data correctly!!! Not good data visualization to say the least. :)

I have set a color function on drop to color individual drops differently based on a type of event. However when I zoom in and out the colors of individual drops change as the merge does not redraw the fill using the color function for drop and simply changes what actual object on the screen is used but not the underlying data associated with that particular dom object so the hover over is still correct. 
**What happened instead:**

      .merge(drops)
        .attr('cx', d => xScale(dropDate(d)));

    // no call to fill or radius..

**Steps to reproduce:**
For instance: in the config use something like 
color: (d, index) => d.surveyId === "GAD-7" ? 'green' : 'red',
Make sure there are enough event objects that when zooming in and out the number of events change that are displayed. You'll see the color change despite the actual data values in the object. 

**Related code:**

```
insert short code snippets here
```

**Other information:**

Here's how I fixed it locally: 

 Wt = function (s, h) {
      return function (t) {
        var e, n, r = s.drop,
          o = r.color,
          u = r.radius,
          a = r.date,
          i = r.onClick,
          c = r.onMouseOver,
          f = r.onMouseOut,
          l = t.selectAll(".drop").data((e = h, n = a, function (t) {
            return $t(t.data, function (t) {
              return Math.round(e(n(t)))
            })
          }));
        l
        .enter().append("circle").classed("drop", !0).on("click", i).on("mouseover", c).on("mouseout", f)
        .merge(l).attr("cx", function (t) {
          return h(a(t))
        }).attr("r", u).attr("fill", o), l.exit().on("click", null).on("mouseover", null).on("mouseout", null).remove()
      }
    };

I also have the meatballs turned off since I am also trying to use my own radius sizing. The important lines are: 
 .enter().append("circle").classed("drop", !0).on("click", i).on("mouseover", c).on("mouseout", f)
        .merge(l).attr("cx", function (t) {
          return h(a(t))
        }).attr("r", u).attr("fill", o), l.exit().on("click", null).on("mouseover", null).on("mouseout", null).remove()
      }

**Environment**

* EventDrops version    "event-drops": "^1.1.1",
* Browser: chrome.
* Stack trace (in case of a JS error):

### LINKED ISSUE #244: Sample code not working anymore
I was trying to get this code up and running.

D3 version: 5.4
event-drops version: 1.2.0

The timeline diagram is showing up, with name property being displayed, but no data point is being potted, there is no error in console.

Regards.

### LINKED ISSUE #257: Bug Correction, Colors and radius drops are flickering on the screen.
# Colors and radius drops are flickering on the screen. #

### I have in my code ###
```
drop : {
                date  :  function(d) { 
                    return moment.unix(d.date_add);
                },
                color :  function(d, index) { 
                    var action = d.action;
                    if (action === 'login') {
                        //console.debug('>>>>>> login', d);
                        return 'green';
                    } else if (action === 'access') {
                        return 'black';
                    } else if (action === 'refresh') {
                        //console.debug('>>>>>> refresh', d);
                        return 'blue';
                    } else if (action === 'logout') {
                        //console.debug('>>>>>> logout', d);
                        console.debug('>>>>>> red logout index', index);
                        return 'red';
                    }
                    console.error('>>>>>> YELLOW ? ', d);
                    return 'yellow';
                },
```
### Then ###
Colors and radius drops are flickering on the screen.

## Bug Origine ##
Bad .merge(drops) usage...

## Bug Correction ##
File : drop.js
### Original ###
```
   drops
        .enter()
        .append('circle')
        .classed('drop', true)
        .attr('r', dropRadius)
        .attr('fill', dropColor)
        .on('click', onClick)
        .on('mouseover', onMouseOver)
        .on('mouseout', onMouseOut)
        .merge(drops)
        .attr('cx', d => xScale(dropDate(d)));
```
### Modified ###
```
   drops
        .enter()
        .append('circle')
        .classed('drop', true)
        .on('click', onClick)
        .on('mouseover', onMouseOver)
        .on('mouseout', onMouseOut)
        .merge(drops)
        .attr('r', dropRadius)
        .attr('fill', dropColor)
        .attr('cx', d => xScale(dropDate(d)));
```

### LINKED ISSUE #258: Bug with global undefined
**What you were expecting:**

A simple example of the chart, taken from issue #244

**What happened instead:**

global_undefined

**Steps to reproduce:**

Go to the link below and download the code. Only google chrome will show stack trace in the console (FireFox doesn't).

**Related code:**

[example code](https://jsfiddle.net/6rqxusw5/9/)
Best to download the code as doing this fix won't work:
insert at top of js code: `var global = window`

**Other information:**

event_drop_window_undefined_fix

Here is a quick way of solving the problem (having `var global = window` at the top is a bit silly).
Will make a PR once in the evening

**Environment**

* EventDrops version 1.3.0
* Browser: Google Chrome Version 70.0.3538.110, FireFox 63.0.3
* Stack trace (in case of a JS error): See image above

### PR DESCRIPTION
**Pull request by Busteren**
Fixes issues where global is undefined and radius and colour flickering after merge. 
This PR also fixes more than the two issues in the title, which can be found in the specific commit message.
Thanks to @christianmerour for his fix on #257, thought I might include it in this PR as it is related to bug fixes.

Prettier did some formatting on index.js.
Please modify as seen fit.

edit:
Fixes #257, fixes #258, fixes #244, fixes #241 and fixes #239

### CODE REVIEW

File: src/drop.js [hunk 1]
```diff
@@ -23,12 +23,12 @@ export default (config, xScale) => selection => {
         .enter()
         .append('circle')
         .classed('drop', true)
-        .attr('r', dropRadius)
-        .attr('fill', dropColor)
         .on('click', onClick)
         .on('mouseover', onMouseOver)
         .on('mouseout', onMouseOut)
         .merge(drops)
+        .attr('r', dropRadius)
```
Comment (jpetitcolas) [inline src/drop.js]: Can you try add a test to ensure it won't break again? Probably by rendering a chart, updating its data and check both radius and color?

Comment (Busteren) [reply src/drop.js]: @jpetitcolas from the issue #241 it seems that in order to test this, the zoom needs to be invoked on the chart. I don't really know how this can be done externally without writing a function that does it. However, the issue does describe the bug in detail. 

Could maybe add enough data and then somehow zoom in and out, then check the data that was outside the viewable area? Could maybe dispatch a zoom event (the custom dispatch ones) and then reset the zoomIdentity, which I think is doable. But I doubt I have time to mess around with this unfortunately.

Comment (jpetitcolas) [reply src/drop.js]: Indeed ,forgot that testing zoom was not done for now. And not sure on how to do it. Merged! :)
